/* eslint-disable @typescript-eslint/no-explicit-any */
import { Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MaterialRequestList } from "@/components/material-request-ui";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const statuses=["pending","approved","partially_approved","issued","rejected","cancelled"];
function malaysiaToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}

export default async function AdminMaterialRequestsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","management_viewer"]);const filters=await searchParams;const supabase=await createClient();const today=malaysiaToday();const start=`${today}T00:00:00+08:00`,end=`${today}T23:59:59.999+08:00`;
  let requestQuery=supabase.from("material_requests").select("id,request_no,status,note,rejection_reason,cancellation_reason,internal_notes,requested_at,approved_at,issued_at,created_at,job:maintenance_jobs!inner(id,job_no,room_no,category,priority,block_id,block:blocks!block_id(code),complaint:complaints!complaint_id(complaint_no)),staff:profiles!requested_by(id,full_name),items:material_request_items(requested_qty,approved_qty,issued_qty,item:inventory_items(item_code,description,category,balance_qty,reorder_level,unit))").order("requested_at",{ascending:false}).limit(200);
  if(filters.status)requestQuery=requestQuery.eq("status",filters.status);if(filters.block)requestQuery=requestQuery.eq("job.block_id",filters.block);if(filters.category)requestQuery=requestQuery.eq("job.category",filters.category);if(filters.priority)requestQuery=requestQuery.eq("job.priority",filters.priority);if(filters.staff)requestQuery=requestQuery.eq("requested_by",filters.staff);if(filters.date)requestQuery=requestQuery.gte("requested_at",`${filters.date}T00:00:00+08:00`).lte("requested_at",`${filters.date}T23:59:59.999+08:00`);
  const[{data:requestRows,error},{data:blocks},{data:staff},{data:categories},{count:pending},{count:approvedToday},{count:issuedToday},{count:rejected},{count:cancelled},{data:attentionRows}]=await Promise.all([
    requestQuery,supabase.from("blocks").select("id,code").order("code"),supabase.from("profiles").select("id,full_name").eq("role","maintenance_staff").eq("is_active",true).order("full_name"),supabase.from("maintenance_jobs").select("category").order("category"),
    supabase.from("material_requests").select("*",{count:"exact",head:true}).eq("status","pending"),supabase.from("material_requests").select("*",{count:"exact",head:true}).in("status",["approved","partially_approved","issued"]).gte("approved_at",start).lte("approved_at",end),supabase.from("material_requests").select("*",{count:"exact",head:true}).eq("status","issued").gte("issued_at",start).lte("issued_at",end),supabase.from("material_requests").select("*",{count:"exact",head:true}).eq("status","rejected"),supabase.from("material_requests").select("*",{count:"exact",head:true}).eq("status","cancelled"),supabase.from("material_request_items").select("request_id,requested_qty,approved_qty,request:material_requests!inner(status),item:inventory_items!inner(balance_qty,reorder_level)").in("request.status",["pending","approved","partially_approved"]),
  ]);
  const attention=new Set((attentionRows??[]).filter((row:any)=>{const stock=Number(row.item?.balance_qty??0),needed=Number(row.approved_qty??row.requested_qty);return stock<needed||stock<=Number(row.item?.reorder_level??0)}).map((row:any)=>row.request_id)).size;
  const search=filters.search?.trim().toLowerCase();const rows=(requestRows??[]).filter((request:any)=>!search||[request.request_no,request.job?.job_no,request.job?.complaint?.complaint_no,request.job?.room_no,request.staff?.full_name,...(request.items??[]).flatMap((row:any)=>[row.item?.item_code,row.item?.description])].some(value=>String(value??"").toLowerCase().includes(search)));
  const categoryOptions=[...new Set((categories??[]).map(row=>row.category))];
  return <AppShell profile={profile} title="Material Requests"><div className="materials-heading"><div><p className="eyebrow">Materials Control</p><h2>Material Request Centre</h2><p className="subtle">Review, approve and issue job materials from one operational queue.</p></div></div>
    {filters.error&&<p className="error">{filters.error}</p>}{filters.success&&<p className="success">Material request updated successfully.</p>}{error&&<p className="error">{error.message}</p>}
    <section className="material-summary">{[["Pending Requests",pending],["Approved Today",approvedToday],["Issued Today",issuedToday],["Rejected",rejected],["Cancelled",cancelled],["Need Attention",attention]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value??0}</strong></article>)}</section>
    <form className="material-filters"><label className="material-search"><Search size={18}/><span className="sr-only">Search material requests</span><input name="search" defaultValue={filters.search} placeholder="Request, job, complaint, room, staff or item"/></label><label><span>Status</span><select name="status" defaultValue={filters.status||""}><option value="">All statuses</option>{statuses.map(status=><option value={status} key={status}>{status.replaceAll("_"," ")}</option>)}</select></label><label><span>Block</span><select name="block" defaultValue={filters.block||""}><option value="">All blocks</option>{blocks?.map(block=><option value={block.id} key={block.id}>Block {block.code}</option>)}</select></label><label><span>Category</span><select name="category" defaultValue={filters.category||""}><option value="">All categories</option>{categoryOptions.map(category=><option key={category}>{category}</option>)}</select></label><label><span>Priority</span><select name="priority" defaultValue={filters.priority||""}><option value="">All priorities</option>{["low","normal","high","urgent"].map(priority=><option key={priority}>{priority}</option>)}</select></label><label><span>Requested By</span><select name="staff" defaultValue={filters.staff||""}><option value="">All staff</option>{staff?.map(member=><option value={member.id} key={member.id}>{member.full_name}</option>)}</select></label><label><span>Date</span><input type="date" name="date" defaultValue={filters.date}/></label><button className="button">Apply</button></form>
    <section className="material-list-panel"><MaterialRequestList rows={rows}/></section>
  </AppShell>;
}
