/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { ArrowLeft, CalendarDays, ExternalLink, PackageOpen, UserRound, X } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PrintJobButton } from "@/components/print-job-button";
import { PriorityBadge, StatusBadge } from "@/components/phase2-ui";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const datePart=(value:string,part:"date"|"time")=>new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",...(part==="date"?{day:"2-digit",month:"short",year:"numeric"}:{hour:"2-digit",minute:"2-digit",hour12:true})}).format(new Date(value));
const duration=(start?:string|null,end?:string|null)=>{if(!start)return null;const minutes=Math.max(0,Math.floor(((end?new Date(end):new Date()).getTime()-new Date(start).getTime())/60000));const hours=Math.floor(minutes/60);const remaining=minutes%60;return hours?`${hours} hr${hours===1?"":"s"}${remaining?` ${remaining} mins`:""}`:`${remaining} mins`};
const actionLabel=(status:string,previous?:string)=>status==="in_progress"?(["pending_material","paused"].includes(previous||"")?"Resumed Work":"Started Work"):({assigned:"Assigned",accepted:"Accepted",paused:"Paused",pending_material:"Pending Material",under_monitoring:"Under Monitoring",completed:"Completed",verified:"Verified",closed:"Closed",reopened:"Reopened",cancelled:"Cancelled"}[status]||status.replaceAll("_"," "));
const progressByStatus:Record<string,number>={assigned:0,accepted:25,in_progress:50,paused:50,pending_material:50,under_monitoring:75,completed:75,verified:100,closed:100,reopened:25,cancelled:0};

export default async function AdminJobDetail({params}:{params:Promise<{id:string}>}){
  const profile=await requireRole(["admin","management_viewer"]);const{id}=await params;const supabase=await createClient();
  const[{data:job},{data:history},{data:requests}]=await Promise.all([
    supabase.from("maintenance_jobs").select("id,job_no,room_no,category,description,priority,status,work_state,scheduled_for,assigned_at,started_at,completed_at,action_taken,pending_material_note,monitoring_note,monitoring_started_at,monitoring_review_at,block:blocks!block_id(code),assignee:profiles!assigned_to(full_name),complaint:complaints!complaint_id(id,complaint_no,complainant_name,submitted_at,reviewed_at,photo_url,reviewer:profiles!reviewed_by(full_name))").eq("id",id).single(),
    supabase.from("job_status_history").select("id,previous_status,new_status,note,created_at,user:profiles!changed_by(full_name)").eq("job_id",id).order("created_at",{ascending:true}),
    supabase.from("material_requests").select("id,request_no,status,note,created_at,reviewed_at,issued_at,requester:profiles!requested_by(full_name),reviewer:profiles!reviewed_by(full_name),issuer:profiles!issued_by(full_name),items:material_request_items(requested_qty,approved_qty,issued_qty,item:inventory_items(item_code,description,unit))").eq("job_id",id).order("created_at",{ascending:true}),
  ]);
  if(!job)notFound();const j:any=job;const complaint:any=j.complaint;const materialRequests=requests??[];const statusHistory=history??[];const progress=progressByStatus[j.status]??0;
  const events:any[]=[
    ...(complaint?.submitted_at?[{key:"complaint-created",at:complaint.submitted_at,user:complaint.complainant_name||"Resident",action:"Complaint Created",remark:j.description}]:[]),
    ...(complaint?.reviewed_at?[{key:"complaint-reviewed",at:complaint.reviewed_at,user:complaint.reviewer?.full_name||"Administrator",action:"Complaint Reviewed",remark:"Approved for maintenance"}]:[]),
    {key:"assigned",at:j.assigned_at,user:complaint?.reviewer?.full_name||"Administrator",action:`Assigned to ${j.assignee?.full_name||"Maintenance staff"}`,remark:"Maintenance job created"},
    ...statusHistory.map((row:any)=>({key:`history-${row.id}`,at:row.created_at,user:row.user?.full_name||"Internal user",action:actionLabel(row.new_status,row.previous_status),remark:row.note||`Status changed from ${actionLabel(row.previous_status)}`})),
    ...materialRequests.flatMap((request:any)=>[
      {key:`request-${request.id}`,at:request.created_at,user:request.requester?.full_name||"Maintenance staff",action:"Material Requested",remark:request.request_no},
      ...(request.reviewed_at?[{key:`review-${request.id}`,at:request.reviewed_at,user:request.reviewer?.full_name||"Administrator",action:request.status==="rejected"?"Material Rejected":"Material Approved",remark:request.note||request.request_no}]:[]),
      ...(request.issued_at?[{key:`issue-${request.id}`,at:request.issued_at,user:request.issuer?.full_name||"Administrator",action:"Material Issued",remark:request.request_no}]:[]),
    ]),
  ].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());
  const timeRows=[["Created Time",complaint?.submitted_at],["Assigned Time",j.assigned_at],["Started Time",j.started_at],["Completed Time",j.completed_at]].filter(([,value])=>value);
  const statusDuration=(status:string)=>statusHistory.reduce((total:number,row:any,index:number)=>{if(row.new_status!==status)return total;const end=statusHistory[index+1]?.created_at||j.completed_at||(j.status===status?new Date().toISOString():row.created_at);return total+Math.max(0,new Date(end).getTime()-new Date(row.created_at).getTime())},0);
  const pausedMs=statusDuration("pending_material");const monitoringMs=statusDuration("under_monitoring");
  const formatMilliseconds=(milliseconds:number)=>{const minutes=Math.floor(milliseconds/60000);const hours=Math.floor(minutes/60);const remaining=minutes%60;return hours?`${hours} hr${hours===1?"":"s"}${remaining?` ${remaining} mins`:""}`:`${remaining} mins`};
  const rawWorkingMs=j.started_at?Math.max(0,(j.completed_at?new Date(j.completed_at):new Date()).getTime()-new Date(j.started_at).getTime()):0;
  return <AppShell profile={profile} title="Maintenance Jobs"><div className="job-drawer-stage"><Link className="drawer-backdrop" href="/admin/jobs" aria-label="Close job"/><aside className="job-drawer" aria-label="Maintenance job details"><header className="drawer-header"><div><Link className="drawer-back" href="/admin/jobs"><ArrowLeft size={16}/> Maintenance Jobs</Link><p className="eyebrow">Work Order</p><h2>{j.job_no}</h2></div><Link className="drawer-close" href="/admin/jobs" aria-label="Close"><X size={20}/></Link></header><div className="drawer-body">
    <div className="job-drawer-badges"><PriorityBadge value={j.priority}/><StatusBadge value={j.status}/></div>
    <section className="job-progress-card"><div className="current-stage-heading"><span>Current Stage</span><strong>{actionLabel(j.status).toUpperCase()}</strong></div><div className="job-progress-meta"><span>Progress</span><strong>{progress}%</strong></div><div className="job-progress-track"><i style={{width:`${progress}%`}}/></div></section>
    <section className="job-info-grid"><div><span>Job Number</span><strong>{j.job_no}</strong></div><div><span>Complaint Number</span><strong>{complaint?.complaint_no||"—"}</strong></div><div><span>Student</span><strong>{complaint?.complainant_name||"Not provided"}</strong></div><div><span>Location</span><strong>Block {j.block?.code} · Room {j.room_no}</strong></div><div><span>Category</span><strong>{j.category}</strong></div><div><span>Assigned Staff</span><strong>{j.assignee?.full_name||"Unassigned"}</strong></div><div className="info-wide"><span>Description</span><p>{j.description}</p></div></section>
    <section className="job-time-grid">{timeRows.map(([label,value])=><div key={label}><span>{label}</span><strong>{datePart(value as string,"date")}</strong><small>{datePart(value as string,"time")}</small></div>)}</section>
    <section className="job-duration-grid"><div><span>Waiting Time</span><strong>{duration(j.assigned_at,j.started_at)||"In progress"}</strong></div><div><span>Working Time</span><strong>{j.started_at?formatMilliseconds(Math.max(0,rawWorkingMs-pausedMs-monitoringMs)):"Not started"}</strong></div><div><span>Paused Duration</span><strong>{formatMilliseconds(pausedMs)}</strong></div><div><span>Monitoring Duration</span><strong>{formatMilliseconds(monitoringMs)}</strong></div><div><span>Total Duration</span><strong>{duration(complaint?.submitted_at,j.completed_at)||"—"}</strong></div></section>
    <section className="drawer-section"><div className="drawer-section-title"><h3>Job Timeline</h3><span>{events.length} recorded events</span></div><div className="job-timeline">{events.map((event,index)=><div key={event.key}><i className={index===events.length-1?"current":""}/><div className="timeline-when"><strong>{datePart(event.at,"date")}</strong><span>{datePart(event.at,"time")}</span></div><div><strong>{event.action}</strong><span><UserRound size={13}/>{event.user}</span>{event.remark&&<small>{event.remark}</small>}</div></div>)}</div></section>
    {(complaint?.photo_url)&&<section className="drawer-section"><div className="drawer-section-title"><h3>Job Photos</h3><span>Available production images</span></div><div className="job-photo-grid"><a className="job-photo-preview" href={complaint.photo_url} target="_blank" rel="noreferrer" style={{backgroundImage:`linear-gradient(#17161233,#17161299),url(${complaint.photo_url})`}}><span>Complaint Photo</span><strong>Open original <ExternalLink size={14}/></strong></a></div></section>}
    {materialRequests.length>0&&<section className="drawer-section"><div className="drawer-section-title"><h3>Materials</h3><span>{materialRequests.length} request{materialRequests.length===1?"":"s"}</span></div><div className="job-materials">{materialRequests.map((request:any)=><article key={request.id}><div><strong>{request.request_no}</strong><span className="badge">{String(request.status).replaceAll("_"," ")}</span></div>{request.items?.map((row:any)=><p key={row.item?.item_code}>{row.item?.item_code} · {row.item?.description}<span>Requested {row.requested_qty} {row.item?.unit||""}{row.issued_qty?` · Issued ${row.issued_qty}`:""}</span></p>)}{request.issued_at&&<small>Issued {datePart(request.issued_at,"date")} · {datePart(request.issued_at,"time")}</small>}<Link href={`/admin/material-requests/${request.id}`}>Open Material Request <ExternalLink size={13}/></Link></article>)}</div></section>}
    {(j.action_taken||j.pending_material_note||j.monitoring_note)&&<section className="drawer-section"><div className="drawer-section-title"><h3>Internal Remarks</h3></div><div className="job-remarks">{j.action_taken&&<div><span>Staff Notes</span><p>{j.action_taken}</p></div>}{j.pending_material_note&&<div><span>Material Note</span><p>{j.pending_material_note}</p></div>}{j.monitoring_note&&<div><span>Monitoring Reason</span><p>{j.monitoring_note}</p></div>}</div></section>}
    {j.work_state==="appointment"&&j.scheduled_for&&<section className="drawer-section job-operational-card"><CalendarDays size={19}/><div><span>Appointment</span><strong>{datePart(`${j.scheduled_for}T00:00:00+08:00`,"date")}</strong></div></section>}
    {j.monitoring_started_at&&<section className="drawer-section job-operational-card"><CalendarDays size={19}/><div><span>Monitoring Period</span><strong>Started {datePart(j.monitoring_started_at,"date")}</strong><small>{j.monitoring_note}{j.monitoring_review_at?` · Review ${datePart(j.monitoring_review_at,"date")}`:""}</small></div></section>}
    {j.status==="completed"&&<section className="drawer-section verification-card"><span>Verification</span><strong>Waiting Verification</strong><small>Verification details will appear when recorded in the production workflow.</small></section>}
    <section className="job-drawer-actions">{complaint?.id&&<Link className="job-drawer-action" href={`/admin/complaints/${complaint.id}`}>Open Complaint <ExternalLink size={15}/></Link>}{materialRequests.length>0&&<Link className="job-drawer-action" href={`/admin/material-requests/${materialRequests[0].id}`}><PackageOpen size={16}/> Open Material Request</Link>}<PrintJobButton/></section>
  </div></aside></div></AppShell>;
}
