/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { ArrowLeft, ExternalLink, PackageCheck, X } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { requestNumber } from "@/components/material-request-ui";
import { PriorityBadge } from "@/components/phase2-ui";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true}).format(new Date(value)):"—";
const quantity=(value:number|null|undefined,unit?:string)=>value==null?"—":`${Number(value).toLocaleString("en-MY")} ${unit||""}`.trim();

export default async function MaterialRequestDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","management_viewer"]);const{id}=await params;const feedback=await searchParams;const supabase=await createClient();
  const[{data:request},{data:movements},{data:audit}]=await Promise.all([
    supabase.from("material_requests").select("id,request_no,status,note,rejection_reason,cancellation_reason,internal_notes,requested_at,approved_at,rejected_at,issued_at,cancelled_at,created_at,requested_by,requester:profiles!requested_by(full_name),approver:profiles!approved_by(full_name),rejector:profiles!rejected_by(full_name),issuer:profiles!issued_by(full_name),canceller:profiles!cancelled_by(full_name),job:maintenance_jobs!job_id(id,job_no,room_no,category,priority,status,block:blocks!block_id(code),complaint:complaints!complaint_id(id,complaint_no)),items:material_request_items(id,inventory_item_id,requested_qty,approved_qty,issued_qty,item:inventory_items(id,item_code,description,category,balance_qty,reorder_level,unit))").eq("id",id).single(),
    supabase.from("inventory_movements").select("id,reference_number,inventory_item_id,quantity,balance_before,balance_after,occurred_at,issuer:profiles!issued_by(full_name)").eq("material_request_id",id).order("occurred_at",{ascending:false}),
    supabase.from("audit_trail").select("id,action,occurred_at,remark,user:profiles!user_id(full_name)").eq("record_type","material_requests").eq("record_id",id).order("occurred_at",{ascending:false}),
  ]);
  if(!request)notFound();const r:any=request;const job:any=r.job;const items:any[]=r.items??[];const movementByItem=new Map((movements??[]).map((movement:any)=>[movement.inventory_item_id,movement]));const canManage=profile.role==="admin";const reviewable=r.status==="pending";const issuable=["approved","partially_approved"].includes(r.status);const cancellable=["pending","approved","partially_approved"].includes(r.status);const reason=r.rejection_reason||r.cancellation_reason||r.note;
  return <AppShell profile={profile} title="Material Requests"><div className="material-drawer-stage"><Link className="drawer-backdrop" href="/admin/material-requests" aria-label="Close material request"/><aside className="material-drawer" aria-label="Material request details"><header className="drawer-header"><div><Link className="drawer-back" href="/admin/material-requests"><ArrowLeft size={16}/> Material Requests</Link><p className="eyebrow">Materials Control</p><h2>{requestNumber(r.request_no)}</h2></div><Link className="drawer-close" href="/admin/material-requests" aria-label="Close"><X size={20}/></Link></header><div className="drawer-body">
    {feedback.error&&<p className="error">{feedback.error}</p>}{feedback.success&&<p className="success">Material request updated successfully.</p>}
    <div className="material-drawer-badges"><PriorityBadge value={job?.priority||"normal"}/><span className={`material-status material-status-${r.status}`}>{label(r.status)}</span></div>
    <section className="material-info-grid"><div><span>Request Number</span><strong>{requestNumber(r.request_no)}</strong></div><div><span>Requested By</span><strong>{r.requester?.full_name||"—"}</strong></div><div><span>Job Number</span><strong>{job?.job_no||"—"}</strong></div><div><span>Complaint Number</span><strong>{job?.complaint?.complaint_no||"—"}</strong></div><div><span>Location</span><strong>Block {job?.block?.code||"—"} · Room {job?.room_no||"—"}</strong></div><div><span>Request Date</span><strong>{dateTime(r.requested_at||r.created_at)}</strong></div><div className="info-wide"><span>Reason</span><p>{reason||"No reason provided."}</p></div>{r.internal_notes&&<div className="info-wide"><span>Internal Notes</span><p>{r.internal_notes}</p></div>}</section>
    <section className="drawer-section"><div className="drawer-section-title"><h3>Requested Items</h3><span>{items.length} item{items.length===1?"":"s"}</span></div><div className="material-items-wrap"><table className="material-items-table"><thead><tr><th>Item Code</th><th>Item Name</th><th>Category</th><th>Current Stock</th><th>Reorder Level</th><th>Requested Qty</th><th>Approved Qty</th><th>Issued Qty</th><th>Balance After Issue</th></tr></thead><tbody>{items.map(row=>{const movement:any=movementByItem.get(row.inventory_item_id);const stock=Number(row.item?.balance_qty||0),reorder=Number(row.item?.reorder_level||0);const warning=stock<=0?"Out of Stock":stock<=reorder?"Need Reorder":stock<Number(row.approved_qty||row.requested_qty)?"Low Stock":null;return <tr key={row.id}><td><strong>{row.item?.item_code}</strong></td><td>{row.item?.description}</td><td>{row.item?.category||"—"}</td><td>{quantity(stock,row.item?.unit)}{warning&&<small className="stock-warning">{warning}</small>}</td><td>{quantity(reorder,row.item?.unit)}</td><td>{quantity(row.requested_qty,row.item?.unit)}</td><td>{quantity(row.approved_qty,row.item?.unit)}</td><td>{quantity(row.issued_qty,row.item?.unit)}</td><td>{quantity(movement?.balance_after,row.item?.unit)}</td></tr>})}</tbody></table></div></section>
    {(r.approved_at||r.issued_at||r.rejected_at||r.cancelled_at)&&<section className="material-lifecycle"><div><span>Approval</span><strong>{dateTime(r.approved_at)}</strong><small>{r.approver?.full_name||""}</small></div><div><span>Issue</span><strong>{dateTime(r.issued_at)}</strong><small>{r.issuer?.full_name||""}</small></div>{r.rejected_at&&<div><span>Rejected</span><strong>{dateTime(r.rejected_at)}</strong><small>{r.rejector?.full_name||""}</small></div>}{r.cancelled_at&&<div><span>Cancelled</span><strong>{dateTime(r.cancelled_at)}</strong><small>{r.canceller?.full_name||""}</small></div>}</section>}
    {(movements??[]).length>0&&<section className="drawer-section"><div className="drawer-section-title"><h3>Inventory Movements</h3><span>Stock ledger</span></div><div className="material-movements">{movements?.map((movement:any)=><article key={movement.id}><PackageCheck size={18}/><div><strong>{movement.reference_number}</strong><span>{quantity(movement.balance_before)} − {quantity(movement.quantity)} = {quantity(movement.balance_after)}</span></div><small>{dateTime(movement.occurred_at)}<br/>{movement.issuer?.full_name}</small></article>)}</div></section>}
    {canManage&&(reviewable||issuable||cancellable)&&<section className="drawer-section material-actions"><div className="drawer-section-title"><h3>Admin Review</h3><span>Actions are recorded in the audit trail</span></div>{reviewable&&<><form method="post" action="/admin/material-requests/action"><input type="hidden" name="requestId" value={r.id}/><input type="hidden" name="returnTo" value={`/admin/material-requests/${r.id}`}/><input type="hidden" name="action" value="partial"/><div className="approval-quantities">{items.map(row=><label key={row.id}><span>{row.item?.item_code} · {row.item?.description}</span><input type="hidden" name="itemId" value={row.id}/><input type="number" name="approvedQty" min="0" max={row.requested_qty} step="0.01" defaultValue={row.requested_qty} required/></label>)}</div><label className="field"><span>Internal note</span><textarea name="reason" rows={3}/></label><div className="material-action-row"><button className="button" type="submit">Approve Quantities</button></div></form><form className="material-approve-all" method="post" action="/admin/material-requests/action"><input type="hidden" name="requestId" value={r.id}/><input type="hidden" name="returnTo" value={`/admin/material-requests/${r.id}`}/><button className="button secondary" name="action" value="approve" type="submit">Approve All</button></form><form className="material-reason-action" method="post" action="/admin/material-requests/action"><input type="hidden" name="requestId" value={r.id}/><input type="hidden" name="returnTo" value={`/admin/material-requests/${r.id}`}/><input name="reason" required placeholder="Rejection reason"/><button className="button danger" name="action" value="reject">Reject</button></form></>}{issuable&&<form method="post" action="/admin/material-requests/action"><input type="hidden" name="requestId" value={r.id}/><input type="hidden" name="returnTo" value={`/admin/material-requests/${r.id}`}/><button className="button" name="action" value="issue">Issue Material</button></form>}{cancellable&&<form className="material-reason-action" method="post" action="/admin/material-requests/action"><input type="hidden" name="requestId" value={r.id}/><input type="hidden" name="returnTo" value={`/admin/material-requests/${r.id}`}/><input name="reason" required placeholder="Cancellation reason"/><button className="button secondary" name="action" value="cancel">Cancel Request</button></form>}</section>}
    {(audit??[]).length>0&&<section className="drawer-section"><div className="drawer-section-title"><h3>Audit Trail</h3><span>Immutable activity history</span></div><div className="material-audit">{audit?.map((event:any)=><div key={event.id}><strong>{label(event.action)}</strong><span>{event.user?.full_name||"System"} · {dateTime(event.occurred_at)}</span>{event.remark&&<small>{event.remark}</small>}</div>)}</div></section>}
    <section className="job-drawer-actions">{job?.id&&<Link className="job-drawer-action" href={`/admin/jobs/${job.id}`}>Open Job <ExternalLink size={14}/></Link>}{job?.complaint?.id&&<Link className="job-drawer-action" href={`/admin/complaints/${job.complaint.id}`}>Open Complaint <ExternalLink size={14}/></Link>}</section>
  </div></aside></div></AppShell>;
}
