import { AppShell } from "@/components/app-shell";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type RecordRow={id:string;record_type:"servicing"|"certificate_license";title:string;provider:string|null;reference_no:string|null;last_completed_date:string|null;next_due_date:string;status:string;notes:string|null};

const dateFormat=new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",day:"2-digit",month:"short",year:"numeric"});
function dueState(date:string){const days=Math.ceil((new Date(date+"T00:00:00").getTime()-Date.now())/86400000);return days<0?"expired":days<=30?"due":"active";}
function statusLabel(value:string){return value.replaceAll("_"," ");}

export default async function CompliancePage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const profile=await requireRole(["admin","management_viewer"]);const q=await searchParams;const db=await createClient();
 const {data,error}=await db.from("compliance_records").select("id,record_type,title,provider,reference_no,last_completed_date,next_due_date,status,notes").order("next_due_date");
 const records=(data||[]) as RecordRow[];const today=new Date();const limit=new Date(today);limit.setDate(today.getDate()+30);
 const expired=records.filter(x=>new Date(x.next_due_date+"T00:00:00")<today).length;const due=records.filter(x=>{const d=new Date(x.next_due_date+"T00:00:00");return d>=today&&d<=limit;}).length;
 const servicing=records.filter(x=>x.record_type==="servicing");const certificates=records.filter(x=>x.record_type==="certificate_license");
 const table=(rows:RecordRow[],empty:string)=><div className="table-wrap"><table className="table inventory-table"><thead><tr><th>Item</th><th>Company / Authority</th><th>Reference</th><th>Last done</th><th>Next due</th><th>Status</th><th>Notes</th></tr></thead><tbody>{rows.length?rows.map(row=>{const state=dueState(row.next_due_date);return <tr key={row.id}><td><strong>{row.title}</strong></td><td>{row.provider||"—"}</td><td>{row.reference_no||"—"}</td><td>{row.last_completed_date?dateFormat.format(new Date(row.last_completed_date+"T00:00:00")):"—"}</td><td><strong>{dateFormat.format(new Date(row.next_due_date+"T00:00:00"))}</strong></td><td><span className={`stock-state ${state==="expired"?"out":state==="due"?"near":"ok"}`}>{state==="due"?"Due within 30 days":state==="expired"?"Expired":statusLabel(row.status)}</span></td><td>{row.notes||"—"}</td></tr>}):<tr><td colSpan={7}>{empty}</td></tr>}</tbody></table></div>;
 return <AppShell profile={profile} title="Servicing & Compliance"><div className="section-head inventory-heading"><div><p className="eyebrow">Admin Control</p><h2>Servicing & Compliance</h2><p className="subtle">Track scheduled servicing, certificates and licences separately from defects.</p></div></div>{q.error&&<p className="error">{q.error}</p>}{q.success&&<p className="success">Record saved successfully.</p>}{error&&<p className="error">{error.message}</p>}
 <section className="inventory-kpis"><article><span>Total Records</span><strong>{records.length}</strong><small>Servicing and compliance items</small></article><article className="warning"><span>Due within 30 days</span><strong>{due}</strong><small>Plan follow-up now</small></article><article className="danger"><span>Expired</span><strong>{expired}</strong><small>Requires immediate attention</small></article><article className="gold"><span>Servicing</span><strong>{servicing.length}</strong><small>Scheduled operational work</small></article></section>
 {profile.role==="admin"&&<section className="panel inventory-form-card"><div className="section-head compact-head"><div><h3>Add servicing or certificate record</h3><p className="subtle">Use Servicing for planned maintenance. Use Certificate / Licence for validity and renewal tracking.</p></div></div><form action="/admin/compliance/action" method="post" className="inventory-form"><label><span>Record type</span><select name="recordType" required><option value="servicing">Servicing</option><option value="certificate_license">Certificate / Licence</option></select></label><label className="span-2"><span>Name</span><input name="title" placeholder="e.g. Lift monthly servicing / Fire Certificate" required/></label><label><span>Company / Authority</span><input name="provider" placeholder="e.g. Sigma / MFE / MBIP"/></label><label><span>Reference No.</span><input name="referenceNo" placeholder="Certificate or contract number"/></label><label><span>Last completed / issued</span><input name="lastCompletedDate" type="date"/></label><label><span>Next service / expiry date</span><input name="nextDueDate" type="date" required/></label><label><span>Status</span><select name="status"><option value="active">Active</option><option value="renewal_in_progress">Renewal in progress</option><option value="completed">Completed</option></select></label><label className="span-2"><span>Remarks / follow-up</span><textarea name="notes" rows={3} placeholder="What Admin needs to follow up"/></label><div className="span-2"><button className="button">Save record</button></div></form></section>}
 <section className="panel inventory-stock-card"><div className="section-head compact-head"><div><p className="eyebrow">Operational Schedule</p><h3>Servicing</h3><p className="subtle">Monthly, quarterly and annual services such as lift, fire system, genset, grass and waste.</p></div></div>{table(servicing,"No servicing records yet.")}</section>
 <section className="panel inventory-stock-card"><div className="section-head compact-head"><div><p className="eyebrow">Validity & Renewal</p><h3>Certificates & Licences</h3><p className="subtle">Certificates, permits, insurance and licences that must remain valid.</p></div></div>{table(certificates,"No certificate or licence records yet.")}</section>
 </AppShell>;
}