/* eslint-disable @typescript-eslint/no-explicit-any */
import { AppShell } from "@/components/app-shell";
import { CopyWhatsAppButton } from "@/components/copy-whatsapp-button";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const labels: Record<string,string> = { morning_tasks:"9:00 AM Morning Daily Task", midday_update:"12:00 PM Midday Update", daily_summary:"4:50 PM Daily Summary", progress_snapshot:"3-Hour Progress Snapshot", inventory_report:"Inventory Report" };
type Props = { searchParams?: Promise<Record<string,string | string[] | undefined>> };
export default async function ReportsPage({ searchParams }: Props) {
  const profile=await requireRole(["admin","management_viewer"]); const supabase=await createClient(); const params=(await searchParams)??{};
  const date=typeof params.date==="string"?params.date:"", block=typeof params.block==="string"?params.block:"", staff=typeof params.staff==="string"?params.staff:"", reportType=typeof params.reportType==="string"?params.reportType:"";
  let reportsQuery=supabase.from("report_snapshots").select("id,report_type,report_date,block_group,whatsapp_text,source,created_at").order("created_at",{ascending:false}).limit(100); if(date)reportsQuery=reportsQuery.eq("report_date",date);if(block)reportsQuery=reportsQuery.eq("block_group",block);if(reportType)reportsQuery=reportsQuery.eq("report_type",reportType);const{data:reports}=await reportsQuery;
  const{data:staffRows}=await supabase.from("profiles").select("id,full_name").eq("role","maintenance_staff").eq("is_active",true).order("full_name");
  let appointmentQuery=supabase.from("appointments").select("id,appointment_date,appointment_time,status,complaint:complaints!complaint_id(complaint_no,room_no,availability_date,availability_time,room_access_permission,appointment_required,block:blocks!block_id(code)),staff:profiles!assigned_staff(full_name)").order("appointment_date",{ascending:false}).order("appointment_time",{ascending:false}).limit(200);if(date)appointmentQuery=appointmentQuery.eq("appointment_date",date);if(staff)appointmentQuery=appointmentQuery.eq("assigned_staff",staff);const{data:appointments}=await appointmentQuery;
  let issueQuery=supabase.from("inventory_issue_history").select("id,qty,issued_at,job_id,staff_id,inventory_items(item_code,description,unit),maintenance_jobs(job_no,room_no,blocks(code)),profiles!inventory_issue_history_staff_id_fkey(full_name)").order("issued_at",{ascending:false}).limit(200);if(staff)issueQuery=issueQuery.eq("staff_id",staff);if(date)issueQuery=issueQuery.gte("issued_at",`${date}T00:00:00+08:00`).lt("issued_at",`${date}T23:59:59+08:00`);const{data:issues}=await issueQuery;
  const filteredIssues=(issues??[]).filter((row:any)=>!block||block==="ALL"||block.includes(row.maintenance_jobs?.blocks?.code??""));
  let adjustmentQuery=supabase.from("inventory_adjustment_history").select("id,adjustment_type,qty,balance_before,balance_after,note,adjusted_at,inventory_items(item_code,description,unit)").order("adjusted_at",{ascending:false}).limit(200);if(date)adjustmentQuery=adjustmentQuery.gte("adjusted_at",`${date}T00:00:00+08:00`).lt("adjusted_at",`${date}T23:59:59+08:00`);const{data:adjustments}=await adjustmentQuery;
  const consumption=new Map<string,{code:string;description:string;qty:number;unit:string}>();for(const row of filteredIssues as any[]){const item=row.inventory_items,key=item?.item_code??"Unknown",current=consumption.get(key)??{code:key,description:item?.description??"",qty:0,unit:item?.unit??""};current.qty+=Number(row.qty??0);consumption.set(key,current);}
  const exportParams=new URLSearchParams();if(date)exportParams.set("date",date);if(block)exportParams.set("block",block);if(staff)exportParams.set("staff",staff);if(reportType)exportParams.set("reportType",reportType);const suffix=exportParams.toString()?`&${exportParams.toString()}`:"";
  const exports=(dataset:string)=><div className="actions"><a className="button secondary button-link" href={`/admin/reports/export?dataset=${dataset}&format=csv${suffix}`}>CSV</a><a className="button secondary button-link" href={`/admin/reports/export?dataset=${dataset}&format=xls${suffix}`}>Excel</a></div>;
  return <AppShell profile={profile} title="Reports">
    <div className="section-head"><div><h2>Reports & WhatsApp Summary</h2><p className="subtle">Daily reports, material usage, consumption analysis and inventory transactions.</p></div></div>
    <div className="panel"><h3>Filters</h3><form method="get" className="inline-form"><input type="date" name="date" defaultValue={date}/><select name="block" defaultValue={block}><option value="">All Blocks</option><option value="AB">A & B</option><option value="CD">C & D</option><option value="ALL">Overall</option></select><select name="staff" defaultValue={staff}><option value="">All Staff</option>{staffRows?.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select><select name="reportType" defaultValue={reportType}><option value="">All Report Types</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="button" type="submit">Apply</button><a className="button secondary button-link" href="/admin/reports">Reset</a></form></div>
    {profile.role==="admin"&&<div className="panel" style={{marginTop:18}}><h3>Generate Report Now</h3><form action="/admin/reports/generate" method="post" className="inline-form"><select name="reportType" defaultValue="progress_snapshot">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="blockGroup" defaultValue="AB"><option>AB</option><option>CD</option><option>ALL</option></select><button className="button" type="submit">Generate Now</button></form></div>}
    <div className="panel" style={{marginTop:18}}><div className="section-head"><h3>Report History</h3>{exports("reports")}</div>{!reports?.length?<div className="empty"><div><strong>No reports yet</strong>Generate one now or wait for the automatic schedule.</div></div>:<div className="mobile-cards" style={{display:"grid"}}>{reports.map(r=><article className="panel record-card" key={r.id}><div className="record-head"><strong>{labels[r.report_type]??r.report_type} · {r.block_group}</strong><span className="badge">{r.source}</span></div><div className="record-meta"><span>{r.report_date}</span><span>{new Date(r.created_at).toLocaleString("en-MY",{timeZone:"Asia/Kuala_Lumpur"})}</span></div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",lineHeight:1.5,marginTop:16}}>{r.whatsapp_text}</pre><CopyWhatsAppButton text={r.whatsapp_text}/></article>)}</div>}</div>
    <div className="panel" style={{marginTop:18}}><div className="section-head"><h3>Appointment Report</h3>{exports("appointments")}</div>{!appointments?.length?<p className="subtle">No appointments for the selected filters.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Appointment Date</th><th>Appointment Time</th><th>Complaint</th><th>Location</th><th>Assigned Staff</th><th>Room Access Permission</th><th>Appointment Required</th><th>Appointment Status</th></tr></thead><tbody>{(appointments as any[]).map(a=><tr key={a.id}><td>{a.appointment_date}</td><td>{a.appointment_time.slice(0,5)}</td><td>{a.complaint?.complaint_no}</td><td>Block {a.complaint?.block?.code} {a.complaint?.room_no}</td><td>{a.staff?.full_name}</td><td>{String(a.complaint?.room_access_permission||"Not set").replaceAll("_"," ")}</td><td>{a.complaint?.appointment_required?"Yes":"No"}</td><td>{String(a.status).replaceAll("_"," ")}</td></tr>)}</tbody></table></div>}</div>
    <div className="panel" style={{marginTop:18}}><div className="section-head"><h3>Material Usage</h3>{exports("material_usage")}</div>{!filteredIssues.length?<p className="subtle">No material issues for the selected filters.</p>:<div className="mobile-cards" style={{display:"grid"}}>{(filteredIssues as any[]).slice(0,50).map(r=><div className="record-card" key={r.id}><strong>{r.inventory_items?.item_code} · {r.inventory_items?.description}</strong><div className="record-meta"><span>{r.qty} {r.inventory_items?.unit??""}</span><span>{r.maintenance_jobs?.job_no} · Block {r.maintenance_jobs?.blocks?.code} {r.maintenance_jobs?.room_no}</span><span>{r.profiles?.full_name}</span></div></div>)}</div>}</div>
    <div className="panel" style={{marginTop:18}}><div className="section-head"><h3>Consumption Analysis</h3>{exports("consumption")}</div>{!consumption.size?<p className="subtle">No consumption for the selected filters.</p>:<div className="mobile-cards" style={{display:"grid"}}>{[...consumption.values()].sort((a,b)=>b.qty-a.qty).map(r=><div className="record-card" key={r.code}><strong>{r.code} · {r.description}</strong><div className="record-meta"><span>Total Used: {r.qty} {r.unit}</span></div></div>)}</div>}</div>
    <div className="panel" style={{marginTop:18}}><div className="section-head"><h3>Inventory Transactions</h3>{exports("inventory_transactions")}</div>{!adjustments?.length?<p className="subtle">No inventory adjustments yet.</p>:<div className="mobile-cards" style={{display:"grid"}}>{(adjustments as any[]).slice(0,50).map(r=><div className="record-card" key={r.id}><strong>{r.inventory_items?.item_code} · {r.inventory_items?.description}</strong><div className="record-meta"><span>{String(r.adjustment_type).replaceAll("_"," ")} · {r.qty} {r.inventory_items?.unit??""}</span><span>{r.balance_before} → {r.balance_after}</span><span>{r.note}</span></div></div>)}</div>}</div>
  </AppShell>;
}
