import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
vi.mock("@/lib/auth",()=>({requireRole:vi.fn().mockResolvedValue({id:"staff",role:"maintenance_staff",full_name:"Assigned Staff",blocks:[]})}));
vi.mock("@/components/app-shell",()=>({AppShell:({children}:{children:React.ReactNode})=><main>{children}</main>}));
function query(result:unknown){const b={select:vi.fn(),order:vi.fn(),then:(resolve:(v:unknown)=>unknown)=>Promise.resolve(result).then(resolve)};b.select.mockReturnValue(b);b.order.mockReturnValue(b);return b;}
const appointments=query({data:[{id:"a1",job_id:"j1",appointment_date:"2026-09-12",appointment_time:"10:00:00",status:"confirmed",remarks:"Call first",job:{job_no:"JOB-1"},complaint:{complaint_no:"CMP-1",room_no:"101",reporter_name:"Tenant",reporter_phone:"0123",complainant_name:null,complainant_contact:null,room_access_permission:"no",block:{code:"A"}},staff:{full_name:"Assigned Staff"}}],error:null});
vi.mock("@/lib/supabase/server",()=>({createClient:vi.fn().mockResolvedValue({from:vi.fn(()=>appointments)})}));
import StaffAppointments from "./page";
describe("staff appointments",()=>{it("shows all assigned appointment details using explicit relationships",async()=>{const html=renderToStaticMarkup(await StaffAppointments());expect(html).toContain('href="/staff/jobs/j1"');expect(html).toContain("View Job");expect(html).toContain("JOB-1");expect(html).toContain("CMP-1");expect(html).toContain("Tenant");expect(html).toContain("0123");expect(html).toContain(">A<");expect(html).toContain(">101<");expect(html).toContain(">No<");expect(html).toContain("Assigned Staff");expect(html).toContain("Call first");const projection=appointments.select.mock.calls[0][0];expect(projection).toContain("appointments_job_id_fkey");expect(projection).toContain("appointment_complaint_id_fkey");expect(projection).toContain("appointments_assigned_staff_fkey");expect(projection).not.toContain("reporter_email");});});
