import Link from "next/link";

const requestNumber=(value:string)=>{const sequence=value.match(/(\d+)$/)?.[1];return sequence?`KLGCR-MR-${sequence.padStart(6,"0")}`:value};
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)):"—";
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

// Related rows follow the narrow selects in the server pages; keeping this UI shape local avoids generated-schema coupling.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function MaterialRequestList({rows}:{rows:any[]}){if(!rows.length)return <div className="empty"><div><strong>No material requests found</strong><span>Adjust the filters or wait for a staff request.</span></div></div>;return <><div className="material-table-wrap desktop-table"><table className="material-table"><thead><tr><th>Request Number</th><th>Job Number</th><th>Complaint Number</th><th>Requested By</th><th>Block</th><th>Room</th><th>Items</th><th>Status</th><th>Request Date</th><th>Approval Date</th><th>Issue Date</th><th>Action</th></tr></thead><tbody>{rows.map(request=><tr key={request.id}><td><Link className="material-row-link" href={`/admin/material-requests/${request.id}`}><strong>{requestNumber(request.request_no)}</strong></Link></td><td>{request.job?.job_no||"—"}</td><td>{request.job?.complaint?.complaint_no||"—"}</td><td>{request.staff?.full_name||"—"}</td><td>Block {request.job?.block?.code||"—"}</td><td>{request.job?.room_no||"—"}</td><td>{request.items?.length||0}</td><td><span className={`material-status material-status-${request.status}`}>{label(request.status)}</span></td><td>{date(request.requested_at||request.created_at)}</td><td>{date(request.approved_at)}</td><td>{date(request.issued_at)}</td><td><Link className="table-action" href={`/admin/material-requests/${request.id}`}>View</Link></td></tr>)}</tbody></table></div><div className="mobile-cards material-mobile-cards">{rows.map(request=><Link className="panel record-card" href={`/admin/material-requests/${request.id}`} key={request.id}><div className="record-head"><strong>{requestNumber(request.request_no)}</strong><span className={`material-status material-status-${request.status}`}>{label(request.status)}</span></div><h3>{request.job?.job_no} · Room {request.job?.room_no}</h3><p>{request.staff?.full_name||"—"} · {request.items?.length||0} item(s)</p><div className="record-meta"><span>Block {request.job?.block?.code}</span><span>{date(request.requested_at||request.created_at)}</span></div></Link>)}</div></>}

export {requestNumber};
