import Link from "next/link";
import { formatDate, titleCase, type ComplaintRow, type JobRow } from "@/lib/phase2";
export function StatusBadge({value}:{value:string}){return <span className={`status-badge status-${value}`}>{titleCase(value)}</span>}
export function PriorityBadge({value}:{value:string}){return <span className={`priority-badge priority-${value}`}>{titleCase(value)}</span>}
const complaintNumber=(value:string)=>{const sequence=value.match(/(\d+)$/)?.[1];return sequence?`KLGCR-CMP-${sequence.padStart(6,"0")}`:value};
const complaintStatus=(value:string)=>({under_review:"Reviewed"}[value]||titleCase(value));
const complaintPriority=(value:string)=>({normal:"Medium",urgent:"Emergency"}[value]||titleCase(value));
const complaintAge=(value:string)=>{const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<60)return `${minutes} min${minutes===1?"":"s"}`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} hr${hours===1?"":"s"}`;const days=Math.floor(hours/24);return `${days} day${days===1?"":"s"}`};
const datePart=(value:string,part:"date"|"time")=>new Intl.DateTimeFormat("en-MY",{timeZone:"Asia/Kuala_Lumpur",...(part==="date"?{day:"2-digit",month:"short",year:"numeric"}:{hour:"2-digit",minute:"2-digit",hour12:true})}).format(new Date(value));
export function ComplaintList({rows}:{rows:ComplaintRow[]}){if(!rows.length)return <div className="empty"><div><strong>No complaints found</strong><span>Adjust the filters or create a manual complaint.</span></div></div>;return <><div className="complaint-table-wrap desktop-table"><table className="complaint-table"><thead><tr><th>Complaint Number</th><th>Block</th><th>Room</th><th>Student</th><th>Category</th><th>Priority</th><th>Status</th><th>Complaint Age</th><th>Assigned Staff</th><th>Created Date</th><th>Created Time</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{complaintNumber(r.complaint_no)}</strong></td><td>Block {r.block?.code||"—"}</td><td>{r.room_no}</td><td>{r.complainant_name||"—"}</td><td>{r.category}</td><td><span className={`priority-badge priority-${r.priority}`}>{complaintPriority(r.priority)}</span></td><td><span className={`status-badge status-${r.status}`}>{complaintStatus(r.status)}</span></td><td><strong className="complaint-age">{complaintAge(r.submitted_at)}</strong></td><td>{r.assignee?.full_name||"Unassigned"}</td><td>{datePart(r.submitted_at,"date")}</td><td>{datePart(r.submitted_at,"time")}</td><td><Link className="table-action" href={`/admin/complaints/${r.id}`}>View</Link></td></tr>)}</tbody></table></div><div className="mobile-cards complaint-mobile-cards">{rows.map(r=><Link className="panel record-card" href={`/admin/complaints/${r.id}`} key={r.id}><div className="record-head"><strong>{complaintNumber(r.complaint_no)}</strong><span className={`status-badge status-${r.status}`}>{complaintStatus(r.status)}</span></div><h3>Block {r.block?.code} · Room {r.room_no}</h3><p>{r.complainant_name||"Student not provided"} · {r.category}</p><div className="record-meta"><span className={`priority-badge priority-${r.priority}`}>{complaintPriority(r.priority)}</span><strong>{complaintAge(r.submitted_at)}</strong></div><small>Assigned: {r.assignee?.full_name||"Unassigned"}</small></Link>)}</div></>}
const jobAge=(value:string)=>complaintAge(value);
const jobDate=(value:string|null|undefined)=>value?datePart(value,"date"):"Not scheduled";
export function AdminJobList({rows}:{rows:JobRow[]}){if(!rows.length)return <div className="empty"><div><strong>No maintenance jobs found</strong><span>Adjust the filters or assign an approved complaint.</span></div></div>;return <><div className="admin-job-table-wrap desktop-table"><table className="admin-job-table"><thead><tr><th>Job No.</th><th>Complaint No.</th><th>Block</th><th>Room</th><th>Assigned Staff</th><th>Category</th><th>Priority</th><th>Status</th><th>Due Date</th><th>Age</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link className="job-row-link" href={`/admin/jobs/${r.id}`}><strong>{r.job_no}</strong></Link></td><td>{r.complaint?.complaint_no||"—"}</td><td>Block {r.block?.code||"—"}</td><td>{r.room_no}</td><td>{r.assignee?.full_name||"Unassigned"}</td><td>{r.category}</td><td><PriorityBadge value={r.priority}/></td><td><StatusBadge value={r.status}/></td><td>{jobDate(r.scheduled_for)}</td><td><strong className="job-age">{jobAge(r.assigned_at)}</strong></td><td><Link className="table-action" href={`/admin/jobs/${r.id}`}>View</Link></td></tr>)}</tbody></table></div><div className="mobile-cards admin-job-mobile">{rows.map(r=><Link className="panel record-card" href={`/admin/jobs/${r.id}`} key={r.id}><div className="record-head"><strong>{r.job_no}</strong><StatusBadge value={r.status}/></div><h3>Block {r.block?.code} · Room {r.room_no}</h3><p>{r.category} · {r.assignee?.full_name||"Unassigned"}</p><div className="record-meta"><PriorityBadge value={r.priority}/><strong>{jobAge(r.assigned_at)}</strong></div><small>Due: {jobDate(r.scheduled_for)}</small><span className="table-action">View Job</span></Link>)}</div></>}
export function JobList({rows,staff=false,compact=false}:{rows:JobRow[];staff?:boolean;compact?:boolean}){if(!rows.length)return <div className="empty"><div><strong>No jobs found</strong><span>{staff?"Assigned work will appear here.":"Assign a complaint to create a job."}</span></div></div>;return <><div className="desktop-table"><table className="table"><thead><tr><th>Job</th>{!compact&&<th>Complaint</th>}<th>Location</th><th>Category</th>{!compact&&<th>Staff</th>}<th>Priority</th><th>Status</th><th>Assigned</th><th>Updated</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link className="text-link" href={staff?`/staff/jobs/${r.id}`:"#"}>{r.job_no}</Link></td>{!compact&&<td>{r.complaint?.complaint_no}</td>}<td>Block {r.block?.code} · {r.room_no}</td><td>{r.category}</td>{!compact&&<td>{r.assignee?.full_name}</td>}<td><PriorityBadge value={r.priority}/></td><td><StatusBadge value={r.status}/></td><td>{formatDate(r.assigned_at)}</td><td>{formatDate(r.updated_at)}</td></tr>)}</tbody></table></div><div className="mobile-cards">{rows.map(r=><Link className="panel record-card" href={staff?`/staff/jobs/${r.id}`:"#"} key={r.id}><div className="record-head"><strong>{r.job_no}</strong><StatusBadge value={r.status}/></div><h3>Block {r.block?.code} · {r.room_no}</h3><p>{r.category} — {r.description}</p><div className="record-meta"><PriorityBadge value={r.priority}/><span>{compact?formatDate(r.updated_at):r.assignee?.full_name}</span></div></Link>)}</div></>}
