/* eslint-disable @typescript-eslint/no-explicit-any */
import { AppShell } from "@/components/app-shell";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

function myDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
const workStates=[['standard','Normal'],['partially_completed','Partially Completed'],['appointment','Appointment'],['kiv','KIV']] as const;

export default async function DailyTasksPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","management_viewer"]);const filters=await searchParams;const date=filters.date||myDate();const supabase=await createClient();const db:any=supabase;
  const[{data:jobs,error},{data:adminTasks}]=await Promise.all([
    db.from("maintenance_jobs").select("id,job_no,room_no,category,status,work_state,scheduled_for,block:blocks!block_id(code),assignee:profiles!assigned_to(full_name)").not("status","in",'("completed","verified","closed","cancelled")').order("scheduled_for",{ascending:true,nullsFirst:false}).order("assigned_at",{ascending:true}),
    db.from("admin_daily_tasks").select("id,task_date,title,notes,status,created_at").eq("task_date",date).order("created_at",{ascending:true})
  ]);
  const isAdmin=profile.role==="admin";
  const rows=(jobs??[]) as any[];const today=rows.filter(r=>r.scheduled_for===date);const unscheduled=rows.filter(r=>!r.scheduled_for);
  const stateForm=(j:any)=>(isAdmin?<form action="/admin/daily-tasks/action" method="post" className="actions"><input type="hidden" name="action" value="work_state"/><input type="hidden" name="jobId" value={j.id}/><input type="hidden" name="date" value={date}/><select name="workState" defaultValue={j.work_state??"standard"}>{workStates.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="button secondary">Save</button></form>:String(j.work_state??"standard").replaceAll("_"," "));
  return <AppShell profile={profile} title="Daily Tasks"><div className="section-head"><div><h2>Daily Task Schedule</h2><p className="subtle">Schedule approved jobs for a working day. The 9AM report uses this list.</p></div><form><input type="date" name="date" defaultValue={date}/><button className="button secondary" style={{marginLeft:8}}>View</button></form></div>
    {filters.error&&<p className="error">{filters.error}</p>}{error&&<p className="error">{error.message}</p>}
    <section className="panel"><div className="section-head"><div><h3>Admin Tasks · {date}</h3><p className="subtle">Office/admin follow-up items included in Phase 5 reporting.</p></div></div>{isAdmin&&<form action="/admin/daily-tasks/action" method="post" className="inline-form"><input type="hidden" name="action" value="admin_task_create"/><input type="hidden" name="date" value={date}/><input name="title" placeholder="Admin task" required/><input name="notes" placeholder="Notes / follow-up"/><button className="button">Add Task</button></form>}<div style={{marginTop:14}}>{!adminTasks?.length?<p className="subtle">No admin tasks for this date.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Task</th><th>Notes</th><th>Status</th><th>Action</th></tr></thead><tbody>{adminTasks.map((t:any)=><tr key={t.id}><td>{t.title}</td><td>{t.notes||"-"}</td><td>{String(t.status).replaceAll("_"," ")}</td><td>{isAdmin?<div className="actions"><form action="/admin/daily-tasks/action" method="post" className="actions"><input type="hidden" name="action" value="admin_task_status"/><input type="hidden" name="taskId" value={t.id}/><input type="hidden" name="date" value={date}/><select name="status" defaultValue={t.status}><option value="pending">Pending</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="kiv">KIV</option></select><button className="button secondary">Update</button></form><form action="/admin/daily-tasks/action" method="post"><input type="hidden" name="action" value="admin_task_delete"/><input type="hidden" name="taskId" value={t.id}/><input type="hidden" name="date" value={date}/><button className="button secondary">Delete</button></form></div>:"Admin only"}</td></tr>)}</tbody></table></div>}</div></section>
    <section className="panel" style={{marginTop:18}}><h3>{date} · Scheduled Maintenance Tasks ({today.length})</h3>{!today.length?<p className="subtle">No jobs scheduled for this date.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Room</th><th>Category</th><th>Staff</th><th>Core Status</th><th>Progress Label</th><th>Schedule</th></tr></thead><tbody>{today.map((j:any)=><tr key={j.id}><td>{j.job_no}</td><td>Block {j.block?.code} {j.room_no}</td><td>{j.category}</td><td>{j.assignee?.full_name}</td><td>{j.status.replaceAll("_"," ")}</td><td>{stateForm(j)}</td><td>{isAdmin?<form action="/admin/daily-tasks/action" method="post" className="actions"><input type="hidden" name="action" value="schedule"/><input type="hidden" name="jobId" value={j.id}/><input type="date" name="date" defaultValue={j.scheduled_for??date}/><button className="button secondary">Change</button></form>:j.scheduled_for}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel" style={{marginTop:18}}><h3>Unscheduled Active Jobs ({unscheduled.length})</h3>{!unscheduled.length?<p className="subtle">All active jobs have a schedule.</p>:<div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Room</th><th>Category</th><th>Staff</th><th>Core Status</th><th>Progress Label</th><th>Add to Day</th></tr></thead><tbody>{unscheduled.map((j:any)=><tr key={j.id}><td>{j.job_no}</td><td>Block {j.block?.code} {j.room_no}</td><td>{j.category}</td><td>{j.assignee?.full_name}</td><td>{j.status.replaceAll("_"," ")}</td><td>{stateForm(j)}</td><td>{isAdmin?<form action="/admin/daily-tasks/action" method="post" className="actions"><input type="hidden" name="action" value="schedule"/><input type="hidden" name="jobId" value={j.id}/><input type="date" name="date" defaultValue={date}/><button className="button">Schedule</button></form>:"Admin only"}</td></tr>)}</tbody></table></div>}</section>
  </AppShell>;
}
