/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { Download, Plus, Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { InventoryList } from "@/components/inventory-ui";
import { PrintInventoryButton } from "@/components/print-inventory-button";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

const categories=["Electrical","Building","Painting","Plumbing","Cleaning","Furniture","Mechanical","Safety","General","Others"];
const since=(days:number)=>new Date(Date.now()-days*86400000).toISOString();
export default async function InventoryPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","management_viewer"]);const filters=await searchParams;const supabase=await createClient();
  const[{data:items,error},{data:recentMovements}]=await Promise.all([
    supabase.from("inventory_items").select("id,item_code,description,category,movement_category,balance_qty,reorder_level,cost,unit,is_active,brand,supplier,storage_location,barcode,minimum_stock,maximum_stock,updated_at").order("category").order("description"),
    supabase.from("inventory_movements").select("inventory_item_id,quantity,movement_type,occurred_at").gte("occurred_at",since(180)).order("occurred_at",{ascending:false}),
  ]);
  const issueTotals=new Map<string,number>(),recent15=new Map<string,number>(),previous15=new Map<string,number>(),lastIssues=new Map<string,string>();for(const movement of recentMovements??[]){if(movement.movement_type!=="out")continue;const occurred=new Date(movement.occurred_at);if(occurred>=new Date(since(30)))issueTotals.set(movement.inventory_item_id,(issueTotals.get(movement.inventory_item_id)||0)+Number(movement.quantity));if(occurred>=new Date(since(15)))recent15.set(movement.inventory_item_id,(recent15.get(movement.inventory_item_id)||0)+Number(movement.quantity));else if(occurred>=new Date(since(30)))previous15.set(movement.inventory_item_id,(previous15.get(movement.inventory_item_id)||0)+Number(movement.quantity));if(!lastIssues.has(movement.inventory_item_id))lastIssues.set(movement.inventory_item_id,movement.occurred_at)}
  const all=items??[];const search=filters.search?.trim().toLowerCase();const rows=all.filter((item:any)=>(!search||[item.item_code,item.description,item.brand,item.supplier,item.category,item.barcode].some(value=>String(value??"").toLowerCase().includes(search)))&&(!filters.category||item.category===filters.category)&&(!filters.movement||item.movement_category===filters.movement)&&(!filters.supplier||item.supplier===filters.supplier)&&(!filters.location||item.storage_location===filters.location)&&(!filters.unit||item.unit===filters.unit)&&(!filters.stock||filters.stock===(item.is_active?(Number(item.balance_qty)<=0?"out":Number(item.balance_qty)<=Number(item.reorder_level)?"near":"in"):"inactive")));
  const value=all.reduce((total,item:any)=>total+Number(item.balance_qty)*Number(item.cost||0),0);const out=all.filter((item:any)=>item.is_active&&Number(item.balance_qty)<=0).length;const near=all.filter((item:any)=>item.is_active&&Number(item.balance_qty)>0&&Number(item.balance_qty)<=Number(item.reorder_level)).length;const fast=issueTotals.size;const slow=all.filter((item:any)=>item.is_active&&!lastIssues.has(item.id)).length;
  const options=(field:string)=>[...new Set(all.map((item:any)=>item[field]).filter(Boolean))].sort();
  return <AppShell profile={profile} title="Inventory"><header className="inventory-heading"><div><p className="eyebrow">Warehouse Control</p><h2>Inventory Management Centre</h2><p className="subtle">Monitor stock, valuation, movement and replenishment from one operational workspace.</p></div><div className="inventory-header-actions"><Link className="button secondary" href="/admin/inventory/export?format=csv"><Download size={15}/> CSV</Link><Link className="button secondary" href="/admin/inventory/export?format=xls"><Download size={15}/> Excel</Link><PrintInventoryButton/>{profile.role==="admin"&&<a className="button" href="#add-inventory"><Plus size={16}/> New Item</a>}</div></header>
    {filters.error&&<p className="error">{filters.error}</p>}{filters.success&&<p className="success">Inventory saved successfully.</p>}{error&&<p className="error">{error.message}</p>}
    <section className="inventory-summary">{[["Total Inventory Items",all.length],["Inventory Value",`RM ${value.toLocaleString("en-MY",{minimumFractionDigits:2,maximumFractionDigits:2})}`],["Fast Moving Items",fast],["Slow Moving Items",slow],["Near Reorder",near],["Out Of Stock",out]].map(([title,count])=><article key={title}><span>{title}</span><strong>{count}</strong></article>)}</section>
    <form className="inventory-filters"><label className="inventory-search"><Search size={18}/><span className="sr-only">Search inventory</span><input name="search" defaultValue={filters.search} placeholder="Code, name, brand, supplier, category or barcode"/></label>{[["category","Category",options("category")],["movement","Movement",["fast","slow","once_in_a_while"]],["supplier","Supplier",options("supplier")],["location","Location",options("storage_location")],["stock","Stock Status",["in","near","out","inactive"]],["unit","Unit",options("unit")]].map(([name,title,values]:any)=><label key={name}><span>{title}</span><select name={name} defaultValue={filters[name]||""}><option value="">All</option>{values.map((option:string)=><option key={option} value={option}>{option.replaceAll("_"," ")}</option>)}</select></label>)}<button className="button">Apply</button></form>
    <section className="inventory-list-panel"><InventoryList rows={rows}/></section>
    <div className="inventory-insight-grid"><section className="inventory-insight"><header><h3>Fast Moving · Last 30 Days</h3><span>Top 10 issued items</span></header>{[...issueTotals.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,qty],index)=>{const item:any=all.find((row:any)=>row.id===id);return <Link href={`/admin/inventory/${id}`} key={id}><b>{index+1}</b><span>{item?.item_code} · {item?.description}</span><strong>{qty.toLocaleString("en-MY")} {item?.unit||""} <i aria-label="Issue trend">{(recent15.get(id)||0)>(previous15.get(id)||0)?"↑":(recent15.get(id)||0)<(previous15.get(id)||0)?"↓":"—"}</i></strong></Link>})}</section><section className="inventory-insight"><header><h3>Slow Moving</h3><span>Time since last issue</span></header>{all.filter((item:any)=>item.is_active&&(!lastIssues.get(item.id)||new Date(lastIssues.get(item.id)!)<new Date(since(30)))).slice(0,10).map((item:any)=>{const last=lastIssues.get(item.id);const days=last?Math.floor((Date.now()-new Date(last).getTime())/86400000):null;return <Link href={`/admin/inventory/${item.id}`} key={item.id}><span>{item.item_code} · {item.description}</span><strong>{days==null?"No issue in 180 days":`${days} days`}</strong></Link>})}</section><section className="inventory-insight"><header><h3>Inventory Value by Category</h3><span>Current valuation</span></header>{[...new Set(all.map((item:any)=>item.category))].map(category=>{const categoryValue=all.filter((item:any)=>item.category===category).reduce((total:number,item:any)=>total+Number(item.balance_qty)*Number(item.cost||0),0);return <div className="inventory-value-row" key={category}><span>{category}</span><strong>RM {categoryValue.toLocaleString("en-MY",{minimumFractionDigits:2,maximumFractionDigits:2})}</strong></div>})}</section></div>
    {profile.role==="admin"&&<section className="panel inventory-create" id="add-inventory"><h3>Add Inventory Item</h3><form action="/admin/inventory/action" method="post" className="form-grid"><input type="hidden" name="action" value="create"/><label><span>Item Code</span><input name="itemCode" required/></label><label><span>Item Name</span><input name="description" required/></label><label><span>Category</span><select name="category" required>{categories.map(category=><option key={category}>{category}</option>)}</select></label><label><span>Movement</span><select name="movement"><option value="fast">Fast Moving</option><option value="slow">Slow Moving</option><option value="once_in_a_while">Once in a while</option></select></label><label><span>Opening Balance</span><input name="balance" type="number" min="0" step="0.01" defaultValue="0" required/></label><label><span>Reorder Level</span><input name="reorder" type="number" min="0" step="0.01" defaultValue="0" required/></label><label><span>Unit</span><input name="unit"/></label><label><span>Average Cost (RM)</span><input name="cost" type="number" min="0" step="0.01"/></label><label><span>Brand</span><input name="brand"/></label><label><span>Supplier</span><input name="supplier"/></label><label><span>Location</span><input name="location"/></label><label><span>Barcode</span><input name="barcode"/></label><div className="field-wide"><button className="button">Add Item</button></div></form></section>}
  </AppShell>;
}
